env:
  es6: true
  browser: true
  node: true
extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 6
  sourceType: "module"
  emacsFeatures: 
     jsx: true
rules:
  indent:
    - error
    - tab
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - always
